name: Release on PR merge

on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: '0'

      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
          check-latest: true

      - run: pnpm install -g lerna@7 pnpm@9
      - run: pnpm install
      - run: pnpm -r run build

      - name: Dry-run publish
        run: |
          pnpm lerna publish from-package -y --no-private --dist-tag latest --yes --no-git-tag-version --loglevel silly --ignore-scripts --registry https://registry.npmjs.org/ || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
